### ISSUE TITLE
Run audit locally

### ISSUE THREAD

**Issue by AfterSpencer** [vulnersCom/api#13]
I have been able to pull down the data locally, but am not sure how to use it in an offline environment:

Download whole database collection and work with data locally
import vulners

vulners_api = vulners.Vulners(api_key="YOUR_API_KEY_HERE")
all_cve = vulners_api.archive("cve")

What is the syntax to use a local copy of the data for offline auditing?

**Comment by vulnersCom** [comment]
Currently there is only one way to audit offline - Vulners commercial on premise installation.

Archive feature is for the integration purposes mostly, to get dataset for local analysis of it.
