### ISSUE TITLE
Unable to pull data of all CVE's in single day from archive

### ISSUE THREAD

**Issue by RSAMINEN** [vulnersCom/api#17]
Hi Vulners Team,
I am trying to pull data from cve with vulnerabilities with in a single day .
I tried to import the vulners source code and change the start date and end date with required values and still seeing that I was pulling all the data.
If possible can you please provide me with a code to pull data of all cves that are observed in a single day.
Your help is much appreciated.
Thank you

**Comment by vulnersCom** [comment]
Example of request:
https://vulners.com/api/v3/archive/collection?type=cve&datefrom=2019-08-07&dateto=2019-08-09

**Comment by RSAMINEN** [comment]
Hello Team, Thanks for the update but when I make a call to the same by passing api-key as header and  type, datafrom and data to as params I still getting the 403 error message, can please help me with that.
thank you

**Comment by RSAMINEN** [comment]
Thnak you Its working.
