### ISSUE TITLE
Can't get distributive / collection results with FREE API Key ?

### ISSUE THREAD

**Issue by ikatolkar** [vulnersCom/api#22]
Hi, 
Earlier I was able to use my free api key to get results for a particular os distribution. But that doesn't seem to work anymore. Have the restrictions changed on API usage? 

**Here's what I'm doing:**
_vulners_api = vulners.Vulners(api_key=API_KEY)
cve_data = vulners_api.distributive("CentOS", "7")
print(type(cve_data))_

**Here's what I get:**
_/usr/local/lib/python3.6/dist-packages/vulners/api.py:155: UserWarning: This method available only for license types: ['professional', 'enterprise', 'oem', 'trial', 'research'], current license set: ['free']
  warnings.warn("%s" % results.get('error'))
Traceback (most recent call last):
  File "./vulnerstest.py", line 5, in <module>
    cve_data = vulners_api.distributive("CentOS", "7")
  File "/usr/local/lib/python3.6/dist-packages/vulners/api.py", line 696, in distributive
    with ZipFile(BytesIO(zipped_json)) as zip_file:
TypeError: a bytes-like object is required, not 'dict'_

**The same result can be seen on https://vulners.com/docs**

**Comment by vulnersCom** [comment]
Hi ikatolkar,
That's correct. Database export is now available only in commercial license.
For companies it is Enterprise license, for personal use - Professional.

**Comment by ikatolkar** [comment]
Thanks for the clarification! 
Could you please also let us know what is accessible with free licence? Is a documentation available?

**Comment by vulnersCom** [comment]
For now - everything except database export.
That is legit for personal use.
