### ISSUE TITLE
Unreachable code error

### ISSUE THREAD

**Issue by nkormakov** [vulnersCom/api#39]
Hi, I've encountered an IDE error "Code is unreachable - Pylance"
<img width="551" alt="image" src="https://user-images.githubusercontent.com/5960099/216596191-e02b6174-4aef-475b-b420-5353527fd680.png">

It is caused by [_\_call__ method in Endpoint class](https://github.com/vulnersCom/api/blob/v2.0/vulners/base.py#L426), which just raising RuntimeError. Adding an annotation to it (I set it to `None` because there's nothing to return, but any other will work too) will fix this error:
<img width="421" alt="image" src="https://user-images.githubusercontent.com/5960099/216597274-84ee4c58-b67b-4c26-a2ba-d9038c25ac65.png">
<img width="547" alt="image" src="https://user-images.githubusercontent.com/5960099/216597327-daa32a27-76ea-43dc-a482-30f2e149de95.png">

I did not create a PR because I'm not sure which branch is the main one for Python library

**Comment by vulnersCom** [comment]
Looks like it's already fixed.
