### ISSUE TITLE
CPE to CVE

### ISSUE THREAD

**Issue by luai24** [vulnersCom/api#41]
So I have a question, what if I want an exact CVE for a CPE, For example, cpe:/a:apache:http_server:2.2.8 should return one vulnerability because I specified the version. I have no clue how to do that using this API. 

Thanks in advance.

**Comment by vulnersCom** [comment]
If you want to get all the vulnerabilities applicable to this CPE you can do it this way:

```
import vulners

vulners_api = vulners.VulnersApi(api_key="<YOR KEY HERE>")
cve_results = vulners_api.get_cpe_vulnerabilities(cpe="cpe:/a:apache:http_server:2.2.8")
print("\n".join(["%s" % _['id'] for _ in cve_results.get('NVD')]))
```
