### ISSUE TITLE
x-vulners-ratelimit-reqlimit

### ISSUE THREAD

**Issue by samosvat** [vulnersCom/api#6]
How to get the value `x-vulners-ratelimit-reqlimit`?
To limit the number of requests per second to vulners.com to the optimal value.
Can you make the VulnersAPI module itself control this timer, transparent to the user?

**Comment by vulnersCom** [comment]
Done in 1.3.0 release.
Check it out [at this commit](https://github.com/vulnersCom/api/commit/edf0fed70203caddddfb4e6136bf8d5351ebba85).

**Comment by samosvat** [comment]
👍
